export const load = async () => {
  return {
    postEntries: [
      {
        id: "001",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "002",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "003",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "004",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "005",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "006",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "007",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "008",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "009",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "010",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "011",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "012",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "013",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "014",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "015",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "016",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "017",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
      {
        id: "018",
        title: "Dolorem corrupti, rerum reprehenderit eum odio",
        brief: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolorem corrupti, rerum reprehenderit eum odio iure libero doloremque ipsam nulla culpa vitae, omnis dicta quidem, alias nobis eaque iste nihil et!",
        date: 0,
        author: "adipisicing",
      },
    ],
  };
};
